<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDWz1VI4\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDWz1VI4/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDWz1VI4.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDWz1VI4\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDWz1VI4\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'DWz1VI4',
    'container.build_id' => '496589a1',
    'container.build_time' => 1543499211,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDWz1VI4');
